### ISSUE TITLE
Do you have sample data for testing?

### ISSUE THREAD

**Issue by wwtinwhu** [KumarRobotics/sloam#1]

**Comment by gnardari** [comment]
Hello, you can find a pre-trained model and  ROS bags [here](https://drive.google.com/drive/u/2/folders/1RjuANtrhq0mfgWYKIFZWIriCozDq-Wc3).

**Comment by nvhungv2k** [comment]
> Hello, you can find a pre-trained model and ROS bags [here](https://drive.google.com/drive/u/2/folders/1RjuANtrhq0mfgWYKIFZWIriCozDq-Wc3).
@gnardari I can't get pre-trained model and ROS bags as you suggested

**Comment by sachman** [comment]
> Hello, you can find a pre-trained model and ROS bags [here](https://drive.google.com/drive/u/2/folders/1RjuANtrhq0mfgWYKIFZWIriCozDq-Wc3).

Hi,
These drive links are not working. Is there anyway we can get the model and the bag?

Also, I am fairly new to ROS -- the ros bag is for creating simulated lidar data?
